name: angry_customer_chatbot
description: "Angry customer chatbot"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.5
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  dio: ^5.7.0
  file_picker: ^8.3.1
  #flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

assets:
  - assets/img/icon.png
  - assets/img/
  - .env
